# Port standard pour le backend (Python/ESP32/MQTT Explorer)
listener 1883
protocol mqtt
allow_anonymous true

# Port WebSocket pour le frontend ( dans le navigateur)
listener 9001
protocol websockets
allow_anonymous true
